### ISSUE TITLE
[NEW FEATURE] Support for sparse matrices

### ISSUE THREAD

**Issue by Ondiz** [ekaitz-zarraga/libmatthread#1]
Most of the elements of a sparse matrix so is a waste of space to store all elements of it. In general this matrices are stored in a _position1, position2, value_ fashion but there are [more ways](http://en.wikipedia.org/wiki/Sparse_matrix#Compressed_sparse_row_.28CSR_or_CRS.29). The problem with that is that algorithms change completely if sparse matrices are used. For example, matrix-vector multiplication will be (from [here](http://stackoverflow.com/questions/15693584/fast-sparse-matrix-multiplication)):
1. Zeroise the result vector, y.
2. Initialise an iterator for the non-zero elements of the matrix, A.
3. Get the next non-zero element of the matrix, A[i,j] say. Note that the pattern of i,j doesn't follow a regular pattern. It simply reflects the order in which the non-zero elements of A are stored.
4. y[i] += A[i,j]*x[j]
5. If there are more elements of A, goto 3.

Support for sparse matrices would be great as it would allow to export data from Finite Element software and perform calculations on them.

**Comment by ekaitz-zarraga** [comment]
Nice!
I'll give it a try later an keep you informed.
Thank you!

**Comment by ekaitz-zarraga** [comment]
This project is unmaintained, it was only for learning and my interests changed.
All the issues are closed but might be reopened in the future.
